name: Documentation

on:
  pull_request:
    paths:
      - '**/*.md'
      - '.github/workflows/docs.yml'
  push:
    branches: [main]
    paths:
      - '**/*.md'
      - '.github/workflows/docs.yml'
  schedule:
    - cron: '31 4 * * 1'

permissions:
  contents: read

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          args: >-
            --root-dir .
            --no-progress
            --exclude '^https?://(?:localhost|127\.0\.0\.1)'
            './**/*.md'
          token: ${{ secrets.GITHUB_TOKEN }}

